#!/bin/bash
# chkconfig: 2345 45 19 
# description:dPhoneGate service
# source function library. 
. /etc/rc.d/init.d/functions 
# check that networking is up. 
[ "${NETWORKING}" = "no" ] && exit 0 
# check for dPhoneGate script 

CATALINA_HOME=/root/depserver/dPhoneGate
PHONEGATE_START=$CATALINA_HOME/start.sh

dphonegate_pid() {
        echo `ps -ef | grep dPhoneGate | grep -v grep | tr -s " "|cut -d" " -f2`
}

if [ ! -f $CATALINA_HOME/start.sh ]; then
        echo -e "\e[00;32m dphonegate not valilable...\e[00m" 
        exit 
fi 

start(){ 
		pid=$(dphonegate_pid)
	if [ -n "$pid" ];then
		echo -e "\e[00;31m dphonegate is already running (pid: $pid)\e[00m"
	else
		echo -e "\e[00;32m Starting dphonegate ...\e[00m"
		cd $CATALINA_HOME/
                daemon $CATALINA_HOME/sstart.sh
        echo 
        touch /var/lock/subsys/dphonegate 
	fi
} 

stop(){
		pid=$(dphonegate_pid) 
		ps ax --width=1000 | grep "[d]PhoneGate" | awk '{printf $1 " "}' \
 | wc | awk '{print $2}' > /tmp/dphonegate_process_count.txt 
		read line < /tmp/dphonegate_process_count.txt
        if [ $line -gt 0 ]; then 
                daemon kill -9 $pid
		echo -e "\e[00;32m dphonegate is shutdown ...\e[00m"
                rm -f /var/lock/subsys/dphonegate
        else 
                echo -e "\e[00;31m dphonegate is stopped \e[00m" 
        fi 
        
        
} 

status(){ 
        ps ax --width=1000 | grep "[d]PhoneGate" | awk '{printf $1 " "}' \
 | wc | awk '{print $2}' > /tmp/dphonegate_process_count.txt 
        read line < /tmp/dphonegate_process_count.txt 
        if [ $line -gt 0 ]; then 
                echo -en "\e[00;31m dphonegate ( pid \e[00m" 
                echo -en "\e[00;31m `ps ax --width=1000 | grep "[d]PhoneGate" | awk '{printf $1 " "}'`\e[00m"
                echo -en "\e[00;31m ) is running...\e[00m" 
                echo 
        else 
                echo -e "\e[00;31m dphonegate is stopped \e[00m" 
        fi 
} 
case "$1" in 
        start) 
                start ;; 
        stop) 
                stop ;; 
        restart) 
		status 
		stop 
		status
		start 
		status ;;
        status) 
                status ;; 
        *) 
                echo "Usage: dphonegate {start|stop|restart|status}" 
                exit 1 
esac 
exit 0 

